from ruby:3.0.0 as runtime

#RUN bundle config --global frozen 1
RUN apt-get update -y && apt-get upgrade -y

WORKDIR pill_api/

copy pill_api/ ./

ENV BUNDLER_VERSION=2.2.3

RUN gem update --system
RUN gem install rails
RUN gem install bundler -v 2.2.3
RUN bundle install
RUN rake app:update:bin
RUN chown -R www-data:www-data /pill_api

EXPOSE 12122
ENV RAILS_ENV=production
ENTRYPOINT ["rails", "s", "-p", "12122", "-b", "0.0.0.0", "-e", "production"]